### PR TITLE
Adding labels to clusters 

### PR DESCRIPTION
**Pull request by courtneymiller2010**
Adding labels to clusters with option of 'top' or 'bottom' (defaults to middle) location using clusterLabelPos as an option for setNode. Should add link to cluster.html from the demo directory to the wiki. Will need to do a make dist to get the cluster.html working. This is in support of issue #140.

### CODE REVIEW

**Comment by cpettitt** [comment]
Looks good! It would be possible to get the edges to route around the cluster label by doing some of this in dagre - e.g. adding a dummy node to the cluster at the right rank with the size of the label.

**Comment by chruetli** [comment]
Looking at the "Clusters" demo (http://cpettitt.github.io/project/dagre-d3/latest/demo/clusters.html) I cannot see any label of cluster. I expect the labels "Group", "Top Group" and "Bottom Group". What's missing?

**Comment by cpettitt** [comment]
Fixed in https://github.com/cpettitt/dagre-d3/pull/180. This will show up in v0.4.9.

**Comment by chruetli** [comment]
Cool, thank you for fast support!

**Pull request merged**
