### PR TITLE
Redo: Add css class to edge, if they have that attribute set

### PR DESCRIPTION
**Pull request by torpedro**
Since there has been no progress on PR https://github.com/cpettitt/dagre-d3/pull/145, I redid the changes of ulilicht, because I think this is an important change to implement.

### CODE REVIEW

**Comment by cpettitt** [comment]
This behaves inconsistently with create-nodes. I'll take the PR if we can get it in sync, which should be a matter of using util.applyClass and adding tests to bundle-test.js.

**Comment by torpedro** [comment]
Good point. I changed the behaviour to be consistent. The css classes are applied on the group object which also has the "edgePath" class. I also added tests for that.

**Comment by cpettitt** [comment]
Thanks! I'll get a build out shortly.

**Comment by cpettitt** [comment]
Published in https://github.com/cpettitt/dagre-d3/releases/tag/v0.4.3.

**Pull request merged**
